### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by rhjp92** [wagnerwagner/merx-starterkit#1]
I've installed the Starter Kit, but after clicking the 'Add to cart' button, I cannot see any products in the cart.

I'm getting a 404 error for `XHR POST http://localhost:8888/api/shop/checkout` and also `XHR GET http://localhost:8888/api/shop/cart`

Additionally, in the checkout when I select a payment option, an error message appears `JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by tobiasfabian** [comment]
Hey @rhjp92,
thank you for trying the Starterkit.

What is happening when you click “Add to cart”? The click creates a `POST` request on `http://localhost:8888/api/shop/cart`. Can you trace this behavior with the help of the dev tools? What’s the response for this request?

404 error for `POST http://localhost:8888/api/shop/checkout` and `GET http://localhost:8888/api/shop/cart` is weird. What is the response text for these requests?

Do you run the Starterkit on a subdirectory? In this case you need to update the [JavaScript](https://github.com/wagnerwagner/merx-starterkit/blob/main/assets/js/cart.js#L75).

The code of the API routes are [there](https://github.com/wagnerwagner/merx-starterkit/tree/main/site/plugins/site/api/routes), maybe this helps for debugging.

**Comment by rhjp92** [comment]
> Do you run the Starterkit on a subdirectory? In this case you need to update the [JavaScript](https://github.com/wagnerwagner/merx-starterkit/blob/main/assets/js/cart.js#L75).

Ah! This was the issue. Thank you.

I've updated `cart.js` with the right path. However, I can't quite figure out how to do that in  `checkout.js` for the checkout route, could you advise? Thanks!

**Comment by tobiasfabian** [comment]
The path for the submit action of the checkout form is defined here: [site/templates/checkout.php#L26](https://github.com/wagnerwagner/merx-starterkit/blob/main/site/templates/checkout.php#L26)

You may also update the path in this line: [assets/js/templates/checkout.js#L101](https://github.com/wagnerwagner/merx-starterkit/blob/main/assets/js/templates/checkout.js#L101)

**Comment by rhjp92** [comment]
Ah of course, please excuse my tired brain!
Thanks for that, most appreciated! Cart and checkout working perfectly now.
