### ISSUE TITLE
Setting quantity to 0 does not remove item from cart

### ISSUE THREAD

**Issue by jamiehunterdesign** [wagnerwagner/merx-starterkit#10]
There is no way to remove an item from the cart as setting the quantity to 0 no longer works. Also not working on the live demo: https://starterkit.merx.wagnerwagner.de/

Maybe a dedicated "remove item" button is better?

**Comment by tobiasfabian** [comment]
Thank you for creating an issue.

It’s fixed with [Merx 1.7.2](https://github.com/wagnerwagner/merx/releases/tag/v1.7.2).

See #11 for more information.
