### ISSUE TITLE
404 on cart api fetch

### ISSUE THREAD

**Issue by tobiasedgar** [wagnerwagner/merx-starterkit#2]
Hi there,

I am getting both these errors on the cart api fetch. 
Everything seems to be installed correctly so I was wondering if I may be missing something regarding the endpoint.

<img width="746" alt="Screen Shot 2022-09-05 at 5 00 05 PM" src="https://user-images.githubusercontent.com/100544490/188363931-c09ff3af-9dd4-4350-9638-6555600c932f.png">

Thanks

**Comment by tobiasfabian** [comment]
Merx itself does not come with an API endpoint nor with JavaScript. Did you use the [Merx Starterkit](https://github.com/wagnerwagner/merx-starterkit/tree/main/site)?

If you created your own implementation, did you create a [custom route](https://getkirby.com/docs/guide/routing) for `api/shop/cart`?

**Comment by tobiasedgar** [comment]
Yes, I am using the Merx starterkit

**Comment by tobiasfabian** [comment]
Can you please look at the response content of `api/shop/cart`. Is it a 404 error page or does it tell you more information about an error?

I’m not sure if the Starterkit works without https. You can try to comment out the security headers ([site/config/config.php](https://github.com/wagnerwagner/merx-starterkit/blob/main/site/config/config.php#L93-L100)), they may not work with localhost.

**Comment by tobiasedgar** [comment]
Hi Tobias, I have managed to get passed the previous error but I am now receiving this error on the add-to-cart click:
<img width="1287" alt="Screen Shot 2022-09-08 at 3 58 54 PM" src="https://user-images.githubusercontent.com/100544490/189031526-99d1d2fc-a096-4f59-b2d9-f1fbda33ddd8.png">

It doesnt seem to pick up the product ID (I am currently using the merx-starterkit product.php)

Thanks

**Comment by tobiasfabian** [comment]
I'm afraid I can't really help you out here. You can double check the request content you are sending to the API endpoint. Does the object include an `id`?

It should look something like this:
```json
{"id":"bike","quantity":1}
```
