### ISSUE TITLE
404 error on api/shop/client-secret fetch  using non-default language

### ISSUE THREAD

**Issue by eqtrd** [wagnerwagner/merx-starterkit#3]
Hi, 

Its seems there is an error with shop/client-secret route. When using non-default language it returns 404 error.

<img width="1154" alt="Capture d’écran 2022-09-12 à 10 10 45" src="https://user-images.githubusercontent.com/52026130/189604555-1f4f6cea-c708-4b35-8b83-6b88b0592c13.png">

I tried changing client-secret.php to : 

```
return [
    'pattern' => '(:any)/shop/client-secret',
    'language' => '*',
    'auth' => false,
    'action' => function () {
        $cart = cart();
        $paymentIntent = $cart->getStripePaymentIntent();
        kirby()->session()->set('ww.site.paymentIntentId', $paymentIntent->id);
        return [
            'clientSecret' => $paymentIntent->client_secret,
        ];
    },
];
```
It has no effect… Any ideas ? 

Thank you

To reproduce :

- Go to starterkit.merx.wagnerwagner.de
- Select Deutsch as language
- Add products to cart
- Try to send Check Out form using credit card payment method

**Comment by tobiasfabian** [comment]
Hi @eqtrd,

thanks for your issue. API routes don’t have a language part. Specifically in this case the `clientSecret` does not depend on the user's language. So you can always call `/api/shop/client-secret`.

There was a bug in `assets/js/templates/checkout.js`. The fetch request of `clientSecret()` should have a leading `/`. b9b18d0fc405f364374e4ec31b3d523f190e2f2e fixes this bug.
