### ISSUE TITLE
Subscription for member with document access

### ISSUE THREAD

**Issue by seyfcom** [wagnerwagner/merx-starterkit#4]
Hi ! 
Your plugin seems great, but I really cannot imagine if it is possible to use it to sell a membership that would give access to docunebts.
I see nothing about customers in your documentation.
Any idea if it would fit or not ?

**Comment by tobiasfabian** [comment]
Hi @seyfcom,
I'm not quite sure what you want to achieve.
Merx does not come with built-in customer management. This is something you will have to build yourself. It is definitely possible to create a (complex) customer management. I think someone has done this before, maybe you can ask in the [forum] (https://forum.getkirby.com/t/merx-plugin-to-create-online-shops-with-kirby-3/13735).
