### ISSUE TITLE
Shipping address isn't working

### ISSUE THREAD

**Issue by eqtrd** [wagnerwagner/merx-starterkit#5]
Hi Tobias, 

I noticed Shipping address isn't working when disabling option "Use billing address as shipping address".
It seems checkbox value is passed to the form only if is checked.
As $data["billingaddressisshippingaddress"] is nonexistent, it results in Order page created with default value (true) for this field and Billing address taken as Shipping one.

**To reproduce :**

Go to starterkit.merx.wagnerwagner.de
Add products to cart
Set different shipping address and billing address
Start the checkout process.

**Possible Fixes**

I tried adding these lines to checkout-post.php (line 10) but it seems to break the creation of order page.
`if(!in_array("billingaddressisshippingaddress", $data)){
            $data = array_merge($data, [
                'billingaddressisshippingaddress' => "off",
            ]);
        }`

May be it has to be done on the checkout.js part before the form is submitted ?

Can you help ? 
Thank you,

**Comment by tobiasfabian** [comment]
Hi @eqtrd,
thanks for your issue.

As you described, if the “Use billing address as shipping address” checkbox is not checked, no value for `billingAddressIsShippingAddress` is transmitted to the server and the field falls back to the default value, which is `true`. I have added a hidden field to [`snippets/fields/toggles.php`](https://github.com/wagnerwagner/merx-starterkit/blob/main/site/snippets/fields/toggle.php) whereby the value `false` for `billingAddressIsShippingAddress` is transmitted when the checkbox is unchecked.

bfc733f8252a1180ca8b68e2ca8975351031ae48
