### ISSUE TITLE
Type Error on upgrade to Kirby 3.9.4

### ISSUE THREAD

**Issue by Jobbies** [wagnerwagner/merx-starterkit#7]
In the Snippet payment-methods.php line 4 
```
  <?php foreach(collection('payment-methods') as $paymentMethod): ?>
```

Throws a type error
```
collection(): Return value must be of type ?Kirby\Cms\Collection, Kirby\Toolkit\Collection returned
```

Maybe it has something todo with this [https://github.com/getkirby/kirby/issues/5169](https://github.com/getkirby/kirby/issues/5169)

**Comment by jamiehunterdesign** [comment]
Just ran into the same error. Updating the `payment-methods` to `Kirby\Cms\Collection` means no payment methods are returned and Stripe is not loaded on the checkout page. Dumping `collection('payment-methods')` returns this:

```
Kirby\Cms\Collection Object
(
    [0] => 0
    [1] => 1
    [2] => 2
    [3] => 3
    [4] => 4
)
```

**Comment by tobiasfabian** [comment]
I will wait for a decision on the Kirby issue [#5169](https://github.com/getkirby/kirby/issues/5169). If they do not revert the change they made in Kirby 3.9.4, I will update the code as mentioned in [this comment](https://github.com/getkirby/kirby/issues/5169#issuecomment-1547784721).

**Comment by tobiasfabian** [comment]
[Kirby 3.9.5](https://github.com/getkirby/kirby/releases/tag/3.9.5) removed the return type for collection helper.

Please update to Kirby 3.9.5.
